#!/usr/bin/env bash
#
# Provision the Multimodal Workplace Chatbot Azure landing zone and write a
# local .env file from the deployment outputs. Idempotent.
#
# Requires: Azure CLI (az) 2.60+, authenticated with `az login`, plus `jq`.
#
# Usage:
#   ./scripts/deploy.sh [-g RESOURCE_GROUP] [-l LOCATION] [-b BASE_NAME] \
#                       [-s SEARCH_LOCATION] [-k SEARCH_SKU] [-p PRIVATE]
#
set -euo pipefail

RESOURCE_GROUP="rg-mmchat"
LOCATION="eastus2"
BASE_NAME="mmchat"
SEARCH_LOCATION="eastus"
SEARCH_SKU="basic"
PRIVATE="false"
DEPLOYMENT_NAME="mmchat-deploy"

while getopts "g:l:b:s:k:p:n:" opt; do
  case $opt in
    g) RESOURCE_GROUP="$OPTARG" ;;
    l) LOCATION="$OPTARG" ;;
    b) BASE_NAME="$OPTARG" ;;
    s) SEARCH_LOCATION="$OPTARG" ;;
    k) SEARCH_SKU="$OPTARG" ;;
    p) PRIVATE="$OPTARG" ;;
    n) DEPLOYMENT_NAME="$OPTARG" ;;
    *) echo "Unknown option"; exit 1 ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INFRA="$REPO_ROOT/infra"

echo "==> Checking Azure login..."
az account show --query "{name:name,id:id}" -o tsv

# Resolve the signed-in user's object id from the ARM token 'oid' claim to
# avoid Microsoft Graph CAE challenges.
echo "==> Resolving deployer object id from access token..."
TOKEN="$(az account get-access-token --query accessToken -o tsv)"
PAYLOAD="$(echo "$TOKEN" | cut -d. -f2 | tr '_-' '/+')"
case $(( ${#PAYLOAD} % 4 )) in 2) PAYLOAD="${PAYLOAD}==";; 3) PAYLOAD="${PAYLOAD}=";; esac
DEPLOYER_OID="$(echo "$PAYLOAD" | base64 -d 2>/dev/null | jq -r .oid)"
echo "    Deployer OID: $DEPLOYER_OID"

echo "==> Creating resource group '$RESOURCE_GROUP' in $LOCATION..."
az group create -n "$RESOURCE_GROUP" -l "$LOCATION" -o none

echo "==> Deploying Bicep (this can take 10-15 minutes)..."
az deployment group create \
  -g "$RESOURCE_GROUP" \
  -n "$DEPLOYMENT_NAME" \
  -f "$INFRA/main.bicep" \
  -p "$INFRA/main.parameters.json" \
  -p baseName="$BASE_NAME" \
  -p location="$LOCATION" \
  -p searchLocation="$SEARCH_LOCATION" \
  -p searchSku="$SEARCH_SKU" \
  -p privateByDefault="$PRIVATE" \
  -p deployerPrincipalId="$DEPLOYER_OID" \
  -o none

echo "==> Reading deployment outputs..."
OUT="$(az deployment group show -g "$RESOURCE_GROUP" -n "$DEPLOYMENT_NAME" \
  --query properties.outputs -o json)"

get() { echo "$OUT" | jq -r ".$1.value"; }

ENV_PATH="$REPO_ROOT/.env"
cat > "$ENV_PATH" <<EOF
# Generated by scripts/deploy.sh on $(date -u +%FT%TZ)
FOUNDRY_PROJECT_ENDPOINT=$(get FOUNDRY_PROJECT_ENDPOINT)
SEARCH_ENDPOINT=$(get SEARCH_ENDPOINT)
SEARCH_INDEX_NAME=workplace-knowledge
STORAGE_ACCOUNT_URL=$(get STORAGE_ACCOUNT_URL)
KEYVAULT_URI=$(get KEYVAULT_URI)
APPLICATIONINSIGHTS_CONNECTION_STRING=$(get APPLICATIONINSIGHTS_CONNECTION_STRING)
AGENT_MODEL_DEPLOYMENT=gpt-4o
VISION_MODEL_DEPLOYMENT=gpt-4o
EMBEDDING_MODEL_DEPLOYMENT=text-embedding-3-large
EOF

echo ""
echo "==> Done. Wrote $ENV_PATH"
echo "Next: python -m src.ingestion.pipeline --ensure-index"
