<#
.SYNOPSIS
    Provision the Multimodal Workplace Chatbot Azure landing zone and write a
    local .env file from the deployment outputs.

.DESCRIPTION
    Idempotent. Creates the resource group (if needed), runs the Bicep
    deployment in infra/, grants the signed-in user data-plane roles for
    setup, and writes deployment outputs to .env at the repo root.

    Requires: Azure CLI (az) 2.60+, authenticated with `az login`.

.EXAMPLE
    ./scripts/deploy.ps1 -ResourceGroup rg-pgr-chatbot -Location eastus2

.EXAMPLE
    ./scripts/deploy.ps1 -ResourceGroup rg-pgr-chatbot -Location eastus2 `
        -SearchLocation eastus -SearchSku basic
#>
[CmdletBinding()]
param(
    [string]$ResourceGroup = "rg-pgr-chatbot",
    [string]$Location = "eastus2",
    [string]$BaseName = "pgrchat",
    [string]$SearchLocation = "eastus",
    [string]$SearchSku = "basic",
    [bool]$PrivateByDefault = $false,
    [string]$DeploymentName = "pgrchat-deploy"
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
$infra = Join-Path $repoRoot "infra"

Write-Host "==> Checking Azure login..." -ForegroundColor Cyan
$account = az account show -o json | ConvertFrom-Json
Write-Host "    Subscription: $($account.name) ($($account.id))"

# Resolve the signed-in user's object id WITHOUT calling Microsoft Graph
# (`az ad ...` can fail with a CAE challenge). We read the 'oid' claim from an
# ARM access token instead.
Write-Host "==> Resolving deployer object id from access token..." -ForegroundColor Cyan
$tok = az account get-access-token --query accessToken -o tsv
$payload = $tok.Split('.')[1].Replace('-', '+').Replace('_', '/')
switch ($payload.Length % 4) { 2 { $payload += '==' } 3 { $payload += '=' } }
$claims = [System.Text.Encoding]::UTF8.GetString(
    [System.Convert]::FromBase64String($payload)) | ConvertFrom-Json
$deployerOid = $claims.oid
Write-Host "    Deployer OID: $deployerOid"

Write-Host "==> Creating resource group '$ResourceGroup' in $Location..." -ForegroundColor Cyan
az group create -n $ResourceGroup -l $Location -o none

Write-Host "==> Deploying Bicep (this can take 10-15 minutes)..." -ForegroundColor Cyan
az deployment group create `
    -g $ResourceGroup `
    -n $DeploymentName `
    -f (Join-Path $infra "main.bicep") `
    -p (Join-Path $infra "main.parameters.json") `
    -p baseName=$BaseName `
    -p location=$Location `
    -p searchLocation=$SearchLocation `
    -p searchSku=$SearchSku `
    -p privateByDefault=$($PrivateByDefault.ToString().ToLower()) `
    -p deployerPrincipalId=$deployerOid `
    -o none

Write-Host "==> Reading deployment outputs..." -ForegroundColor Cyan
$outputs = az deployment group show -g $ResourceGroup -n $DeploymentName `
    --query properties.outputs -o json | ConvertFrom-Json

$envPath = Join-Path $repoRoot ".env"
$lines = @(
    "# Generated by scripts/deploy.ps1 on $(Get-Date -Format o)",
    "FOUNDRY_PROJECT_ENDPOINT=$($outputs.FOUNDRY_PROJECT_ENDPOINT.value)",
    "SEARCH_ENDPOINT=$($outputs.SEARCH_ENDPOINT.value)",
    "SEARCH_INDEX_NAME=workplace-knowledge",
    "STORAGE_ACCOUNT_URL=$($outputs.STORAGE_ACCOUNT_URL.value)",
    "KEYVAULT_URI=$($outputs.KEYVAULT_URI.value)",
    "APPLICATIONINSIGHTS_CONNECTION_STRING=$($outputs.APPLICATIONINSIGHTS_CONNECTION_STRING.value)",
    "AGENT_MODEL_DEPLOYMENT=gpt-4o",
    "VISION_MODEL_DEPLOYMENT=gpt-4o",
    "EMBEDDING_MODEL_DEPLOYMENT=text-embedding-3-large"
)
$lines | Set-Content -Path $envPath -Encoding UTF8

Write-Host "`n==> Done. Wrote $envPath" -ForegroundColor Green
Write-Host "    Foundry project: $($outputs.FOUNDRY_PROJECT_ENDPOINT.value)"
Write-Host "    Search endpoint: $($outputs.SEARCH_ENDPOINT.value)"
Write-Host "`nNext: create the search index" -ForegroundColor Yellow
Write-Host "    python -m src.ingestion.pipeline --ensure-index"
